### ISSUE TITLE
Might not be compatible with biomes o plenty

### ISSUE THREAD

**Issue by abielaird** [Tfarcenim/CIT-Reforged#10]
So i have biomes o plenty and using optifine with it kept corrupting my world, so instead i downloaded citresewn hoping it would fix the problem but the a similar problem happened. I tried to load into my worl and it was stuck on the loading screen. After removing the mod i was able to get on my world again. Im hoping you guys can help me fix this problem, ive waited months for the 1.20.1 version of your mod :(.

There is no crash log available, so i guess it didn't crash. Im not sure what files i should give you.

**Comment by Tfarcenim** [comment]
If the world is corrupted, there's nothing I can do and it has nothing to do with this mod.
