### ISSUE TITLE
1.20.1 emissives do not work

### ISSUE THREAD

**Issue by GrandmaPork** [Tfarcenim/CIT-Reforged#12]
I have noticed that when using optifine, my emissives work fine but when I use this mod, none of my items have emissive textures. blacks too i believe. using latest version on forge

**Comment by GrandmaPork** [comment]
![2024-01-24_14 13 41](https://github.com/Tfarcenim/CIT-Reforged/assets/109642282/eb4283a5-e977-4be3-9ee7-f677b85954a0)
cit reforged

**Comment by GrandmaPork** [comment]
optifine
![2024-01-24_14 10 39](https://github.com/Tfarcenim/CIT-Reforged/assets/109642282/db3cde3c-3b7d-4953-b78d-cdc7bd35b563)

**Comment by Tfarcenim** [comment]
Out of scope, this mod has never added emissive textures
