### ISSUE TITLE
[Crash] IBE Editor Incompatibility

### ISSUE THREAD

**Issue by gaussandhisgun** [Tfarcenim/CIT-Reforged#2]
Turns out, the one and only ingame NBT editor for the game, [IBE Editor](https://www.curseforge.com/minecraft/mc-mods/ibe-editor), tries to do something with a mixin provided by CIT Reforged, and ultimately fails. No matter how bad Optifine is, this does not happen with it. Here's your stack trace: https://katb.in/validmunches

Yeeting IBE Editor *or* Forge CIT does remove the crash, and that's fine while I play on SMPs, but still, having a fancy item editor on hand *will* come in handy one day or another.

**Comment by Tfarcenim** [comment]
fixed in 1.20.1-4
