### ISSUE TITLE
CIT armor doesn't work

### ISSUE THREAD

**Issue by ghost** [Tfarcenim/CIT-Reforged#3]
Forge CIT only changes the icon of armor.
![image](https://github.com/Tfarcenim/CIT-Reforged/assets/129179911/1db73d4c-66ca-4c01-98c3-0f4106575864)

Broken resourcepack:https://www.planetminecraft.com/texture-pack/totem-armor-optifine-required/

**Comment by Tfarcenim** [comment]
Fixed in 5
