### ISSUE TITLE
Wool/Colored block based CIT's Don't Work

### ISSUE THREAD

**Issue by FatherPigeon** [Tfarcenim/CIT-Reforged#5]
I'm having an issue getting wool/colored blocks-based CITS to work for me. The CIT pack itself works fine, but there are some models that use wool for certain colors and they don't work
Here's an example of my issue:
![2023-11-19_02 59 15](https://github.com/Tfarcenim/CIT-Reforged/assets/98893421/5b6ffd98-b661-426c-876b-43ff58dd261a)

**Comment by Tfarcenim** [comment]
3 things:
1) Do you have a copy of the CIT pack?
2) Does it work as intended on Optifine?
3) Does it work as intended on CIT Resewn (fabric)?

**Comment by FatherPigeon** [comment]
Hi, yes I have a copy of the pack. It's worked on both Fabiric and Optifine. It has also worked on previous versions of Minecraft forge with a cit mod before

**Comment by Tfarcenim** [comment]
Could you send it so I can see what's wrong?

**Comment by FatherPigeon** [comment]
of course! Here's the file 
[equestrian-cit-v4-0.zip](https://github.com/Tfarcenim/CIT-Reforged/files/13422581/equestrian-cit-v4-0.zip)

**Comment by Tfarcenim** [comment]
The issue is broken resourcelocations, did you check the log?

Minecraft throws an error when it encounters capitals or spaces and while optifine and the older CIT mods patch it out, I'm not doing it because 

A: it slows down the game

B: it hides more serious errors from other mods

C: it's a pain in the ass to patch and maintain for no benefit when resourcepack makers can fix what's been broken since 1.13

Here's a snippet

> [01:46:58] [Worker-Main-10/ERROR] [CITResewn/]: {citresewn} Couldn't load CIT: JsonParseException: block/Blanket Rack Colors/blanket_rack_orange is not valid resource location in file/equestrian-cit-v4-0 -> minecraft:optifine/cit/blanket_rack_orange.properties
> [01:46:58] [Worker-Main-10/ERROR] [CITResewn/]: {citresewn} Couldn't load CIT: JsonParseException: block/Grooming Box Colors/grooming_box_orange is not valid resource location in file/equestrian-cit-v4-0 -> minecraft:optifine/cit/grooming_box_orange.properties
> [01:46:58] [Worker-Main-10/ERROR] [CITResewn/]: {citresewn} Couldn't load CIT: JsonParseException: block/Jolly Ball Colors/jolly_ball_orange is not valid resource location in file/equestrian-cit-v4-0 -> minecraft:optifine/cit/jolly_ball_orange.properties

**Comment by Tfarcenim** [comment]
The solution is to fix the paths so it no longer throws an error, it is not a bug in the mod
