### ISSUE TITLE
startup crash when cull leaves is present

### ISSUE THREAD

**Issue by kaairu** [Tfarcenim/CIT-Reforged#6]
crashes on startup with https://www.curseforge.com/minecraft/mc-mods/cull-leaves

https://gist.github.com/kaairu/78b3748e6934ea2f626ae247217ed704
https://gist.github.com/kaairu/d077445076dd9519d63d341bd0cec4fb

forge: 47.2.1
1.20.1 
cit reforged ver: 5

**Comment by Tfarcenim** [comment]
Has nothing to do with CIT
> [22:33:49] [main/ERROR]: Missing or unsupported mandatory dependencies:
	Mod ID: 'midnightlib', Requested by: 'cullleaves', Expected range: '[1.0.0,)', Actual version: '[MISSING]'

**Comment by kaairu** [comment]
mb, CF didn't download the dependency :/
