### ISSUE TITLE
Everything is missing textures with Sinytra connector mod

### ISSUE THREAD

**Issue by MacatMovie** [Tfarcenim/CIT-Reforged#9]
Hai. I know it's probably a screech to expect a mod ported from fabric to forge to work with a mod that makes fabric mods playable on forge, but I still decided that t's worth to mention it here.

The thing is that the original fabric CIT resewn works with sinytra connector, but by "works" I mean that the game runs, but it doesn't actually do anything. The game with CIT resewn for forge alongside sinytra connector opens and runs, but it makes pretty much every texture missing.

**Comment by Tfarcenim** [comment]
Connector is unsupported.

**Comment by vinnyg0621** [comment]
wait, why??

**Comment by Tfarcenim** [comment]
Because it breaks mods, take it up with them

https://github.com/Sinytra/Connector/issues

**Comment by MacatMovie** [comment]
@vinnyg0621, @Tfarcenim I recently tested it again with the latest versions and it's working on forge with the latest versions connector mod & CIT resewn for fabric. Thanks for the responses!
